### ISSUE TITLE
erreur durant le peuplement de la base avec Docker

### ISSUE THREAD

**Issue by GregSino** [etalab/sirene_as_api#315]
Bonjour,

J'ai suivi l'ensemble des étapes d'installation avec Docker. Les deux containers tournent, j'ai pu créer la base et la migrer mais j'ai cette erreur durant le "populate" :

```
root@3faa01c28fb6:/docker_build# bundle exec rake sirene_as_api:populate_database
/usr/local/bundle/gems/pry-byebug-3.8.0/lib/pry-byebug/control_d_handler.rb:5: warning: control_d_handler's arity of 2 parameters was deprecated (eval_string, pry_instance). Now it gets passed just 1 parameter (pry_instance)
** Invoke sirene_as_api:populate_database (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute sirene_as_api:populate_database
------>  Visiting monthly stock distant directory
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/docker_build/app/interactors/get_last_monthly_stock_link.rb:19:in `call'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:143:in `block in run!'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:213:in `block in with_hooks'
/docker_build/app/interactors/get_last_monthly_stock_link.rb:10:in `block in <class:GetLastMonthlyStockLink>'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:263:in `instance_exec'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:263:in `run_hook'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:223:in `block (2 levels) in run_around_hooks'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:224:in `run_around_hooks'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:211:in `with_hooks'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:142:in `run!'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:76:in `tap'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:76:in `call!'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/organizer.rb:79:in `block in call'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/organizer.rb:78:in `each'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/organizer.rb:78:in `call'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:143:in `block in run!'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:213:in `block in with_hooks'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:224:in `run_around_hooks'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:211:in `with_hooks'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:142:in `run!'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:76:in `tap'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:76:in `call!'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/organizer.rb:79:in `block in call'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/organizer.rb:78:in `each'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/organizer.rb:78:in `call'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:143:in `block in run!'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:213:in `block in with_hooks'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:224:in `run_around_hooks'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor/hooks.rb:211:in `with_hooks'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:142:in `run!'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:115:in `run'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:50:in `tap'
/usr/local/bundle/gems/interactor-3.1.2/lib/interactor.rb:50:in `call'
/docker_build/lib/tasks/sirene_as_api.rake:24:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => sirene_as_api:populate_database
```

J'ai pourtant déjà fait plusieurs fois cette opération avec succès sur un autre serveur mais là rien n'y fait. Est-il possible qu'il y ait un lien avec la récente maj?

**Comment by GregSino** [comment]
J'ai résolu le problème : 

Vous avez actuellement un problème de lien pour aller récupérer le .csv

Nous avons commenté la ligne 19 de /app/interactors/get_last_monthly_stock_link.rb et ajouté une ligne comme ceci : 

```
require 'nokogiri'
require 'open-uri'
require 'net/http'

class GetLastMonthlyStockLink < SireneAsAPIInteractor
  around do |interactor|
    stdout_info_log 'Visiting monthly stock distant directory'
    fail_server_unavailable unless available?(files_domain)

    interactor.call

    stdout_success_log "Retrieved last monthly stock link name : #{context.link}"
    fail_link_unavailable unless available?(context.link)
    puts
  end

  # Current adress : http://data.cquest.org/geo_sirene/year-month/geo-sirene.csv.gz
  def call
   #last_stock_month_folder = available_stocks_month_folders.last[:href]
    last_stock_month_folder = "/v2017/last/"
    context.link = "#{files_repository}/#{last_stock_month_folder}etablissements_actifs.csv.gz"
  end
```
